# Build and deploy vue app
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      tags:
        description: "Run workflow"
env:
  NODE_VERSION: "20.x"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: yarn install and build
        run: |
          yarn install
          yarn build
